### ISSUE TITLE
Broken Site Link 

### ISSUE THREAD

**Issue by mananbansal2002** [you-dont-need/You-Dont-Need-JavaScript#107]
When we try to open the site deployment it shows page doesn't exit Error 404

https://you-dont-need.github.io/You-Dont-Need-JavaScript/

Correct Link needs to be added

**Comment by 201B153** [comment]
yes, deployment link is broken.

**Comment by Priyanshu-su30** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by mehraankush** [comment]
i want to try ..
