### ISSUE TITLE
README.md update

### ISSUE THREAD

**Issue by si88har1h** [you-dont-need/You-Dont-Need-JavaScript#108]
in the very first line the word "that" is missing which makes it semantically incorrect.

**Comment by RiteshMohan186** [comment]
can you please mark this with the hacktoberfest label? I would like to work on this issue please!

**Comment by Vidip-Ghosh** [comment]
At the last line "Welcome to contribute to this project", It should be "Welcome and contribute."

**Comment by KENILSHAHH** [comment]
Hello, I would love work on this issue, please assign it to me

**Comment by Shivani1917** [comment]
Updated with some changes #126

**Comment by katarisreelasya** [comment]
I would like to update the readme file and fill the empty blocks with its code and some data, like Carousel with its explaination and sample code insted of keeping it empty.   please assign me this task
