### ISSUE TITLE
Add neon button animation

### ISSUE THREAD

**Issue by nikhilkalburgi** [you-dont-need/You-Dont-Need-JavaScript#135]
PR #132 solves this issue

**Comment by riddhitech** [comment]
Please assign this issue to me.

**Comment by Neetika146** [comment]
plz assign  me this

**Comment by Arnab2002Pal** [comment]
I want to ccontribute in this

**Comment by debnath003** [comment]
pls assign me this issue, I want to contribute this issue

**Comment by vedansh2001** [comment]
I want to contribute to this issue. Please assign it to me.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by harshul-2002** [comment]
please assign this to me sir

**Comment by stevemao** [comment]
you can just create a PR if you want to work on this

**Comment by DevanshKyada27** [comment]
Hey @stevemao can you assign this issue to me is possible.
