### ISSUE TITLE
Neon button animation pictutre/gif

### ISSUE THREAD

**Issue by Monika-Sivakumar-3** [you-dont-need/You-Dont-Need-JavaScript#153]
In the readme file we don't have a demo gif for neon button instead we have a ')' which is added in the readme file
<img width="1192" alt="Screenshot 2023-10-04 at 12 57 00 PM" src="https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/111675738/38880331-fd22-4d5e-97e0-fea3829fdb54">

Solution:
Upload gif (neon-button.gif) in the images folder
![neon-button](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/111675738/4bd6fd10-2f25-429a-9886-b76069a36818)

**Comment by DannyK05** [comment]
Can I work on this for the hacktoberfest

**Comment by TUSHARGOTHWAL** [comment]
Can i do this??

**Comment by SamsShow** [comment]
I think this issue is already resolved please close the issue.
