### ISSUE TITLE
Want To Add Simple Animation Using Pure CSS

### ISSUE THREAD

**Issue by pabitra0011** [you-dont-need/You-Dont-Need-JavaScript#158]
please, assing me this issue

**Comment by Priyanshu-ai902** [comment]
Hi, steve i am very interested in this issue 
please, assign me this issue

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by harshul-2002** [comment]
@pabitra0011   please assign this issue to me , is it still open?

**Comment by stevemao** [comment]
you can just create a PR if you want to work on this

**Comment by AnshuWorld** [comment]
i can do it please give me permission

**Comment by PritamP20** [comment]
is this repo still active?

**Comment by stevemao** [comment]
> you can just create a PR if you want to work on this

**Comment by aayush105** [comment]
> is this repo still active?

Yes, You can work on this, as well as the other HTML CSS projects, I will go through it and merge the PR.

**Comment by Kedarnath-Rothe** [comment]
Please Assign this issue to me..... And label this issue under #Hacktoberfest

**Comment by aayush105** [comment]
> Please Assign this issue to me..... And label this issue under #Hacktoberfest

You are already assigned to this issue a long time ago, just work on it and please follow the contributing.md file format like add the code in the respective folder where it belong to and also add the output image in table and in description while creating PR.
