### ISSUE TITLE
Add simple Moving Road Animation Using Power of CSS

### ISSUE THREAD

**Issue by pabitra0011** [you-dont-need/You-Dont-Need-JavaScript#168]

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by pabitra0011** [comment]
I am not maintainer of this project , so you just simply make a PR tag with this issue number.

**Comment by Kedarnath-Rothe** [comment]
https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/143418802/b7860aa4-b679-4b7b-bc2d-7efae5f25faa

@stevemao  Please see my PR....

**Comment by Kedarnath-Rothe** [comment]
I have solved one more issue "Simple Moving Road Animation Using Power of CSS" 
Please see my PR....
