### ISSUE TITLE
Adding a Author Page using simple CSS.

### ISSUE THREAD

**Issue by CrypticRevenger** [you-dont-need/You-Dont-Need-JavaScript#172]
@you-dont-need Please assign me , I want to work on it.

**Comment by CrypticRevenger** [comment]
@stevemao Sir can you please add the [hacktoberfest2023] , [hacktoberfest] and [hacktoberfest-accepted] Label.
I will be very thankful to you.

**Comment by stevemao** [comment]
It has already been added. once your PR is merged, you'll get rewarded
