### ISSUE TITLE
Github badge in the README

### ISSUE THREAD

**Issue by SusheelThapa** [you-dont-need/You-Dont-Need-JavaScript#178]
![Screenshot from 2023-10-11 13-39-56](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/83917129/3dfb0655-cb02-47bd-8fd3-fc4c519781b1)

I want to contribute to this repository by adding above shown badge to the repository.

Please assign me this issue.

**Comment by malivinayak** [comment]
@stevemao 
I just reviewed the PR made by @SusheelThapa 
The License badge should be updated i.e. custom made 
![image](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/66154908/c2f03ad6-ecfe-4c31-ad64-4a0d09180480)

**Comment by VBPMP** [comment]
please, Assign me this issue
