### ISSUE TITLE
Adding Code of Conduct to the repository!

### ISSUE THREAD

**Issue by mohitd404** [you-dont-need/You-Dont-Need-JavaScript#184]
We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will serve as a guideline for behavior, promoting diversity, reducing conflicts, and attracting a wider range of perspectives.

@stevemao kindly assign me this issue, I would love to work on it !

**Comment by mohitd404** [comment]
@stevemao kindly assign me this issue, I would love to work on it !

**Comment by stevemao** [comment]
Just send the PR

**Comment by mohitd404** [comment]
Added PR for #184
