### ISSUE TITLE
Menu demo

### ISSUE THREAD

**Issue by pickfire** [you-dont-need/You-Dont-Need-JavaScript#27]
Since I am still finding ways to do a menu without javascript that is responsive, I found quite a few links:

http://output.jsbin.com/sevula/2/#navbar
https://hpbn.co/building-blocks-of-tcp/ (partial javascript, but the smooth menu opens without javascript)
http://webdesignerwall.com/demo/responsive-menu/ (choose-able)

**Comment by stevemao** [comment]
PR welcome. Please mind the quality of the demo too. Thanks!

**Comment by clumsydog933** [comment]
Hey, I'd like to work on this issue. Can you please assign it to me?
