### ISSUE TITLE
change backgound color of this toogle 

### ISSUE THREAD

**Issue by techmannih** [you-dont-need/You-Dont-Need-JavaScript#283]
white background is not visible directly , change similiar to on hover as black background .
I want to work on this issue
![Screenshot_2023-10-21_08-59-47](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/125847751/64ed2124-aa6e-4374-aad5-41d7af14144b)

**Comment by arezooHND** [comment]
Hi, please assign this issue to me.
