### ISSUE TITLE
feat:  Infinite Carousel 

### ISSUE THREAD

**Issue by purnasth** [you-dont-need/You-Dont-Need-JavaScript#312]
# Issue Title: Infinite Carousel 

## Issue Description:
I propose the addition of a new project `Infinite Carousel` to the **You-Dont-Need-JavaScript** repository. 

## Project Details:
- **Name**: Infinite Image Slider
- **Technologies**: HTML, CSS

## Additional Information (if available):
If there are any specific guidelines or requirements for contributing to the repository, please provide the necessary details

Thank you for your attention to this feature request.

**Comment by aayush105** [comment]
@purnasth  you can contribute to the repository and you can read the CONTRIBUTING.md for further detail information.
And look through the example folder to ensure whether the project you are going to contribute is already done by someone or not.

**Comment by purnasth** [comment]
So, this was the issue I created but Mr. shreenarayan123 opened a PR for this issue without being assigned to do so. Now, shall I work on it or not ? @aayush105

**Comment by aayush105** [comment]
> So, this was the issue I created but Mr. shreenarayan123 opened a PR for this issue without being assigned to do so. Now, shall I work on it or not ? @aayush105 

You can do, as he has conflict in his PR and requested him to resolve it but he hasn't resolved yet. If your code is ready then push it, review will be done and will merge it.
Thank you !!! @purnasth

**Comment by purnasth** [comment]
Can I get assigned please ? @aayush105

**Comment by aayush105** [comment]
> Can I get assigned please ? @aayush105 

Sure !! Start your contribution in the repository.
