### ISSUE TITLE
feat: CSS Loader

### ISSUE THREAD

**Issue by purnasth** [you-dont-need/You-Dont-Need-JavaScript#332]
# Issue Title: CSS Loader

## Issue Description:
I propose adding a new project `CSS Loader` to the **You-Dont-Need-JavaScript** repository. 

## Project Details:
- **Name**: CSS Loader
- **Technologies**: HTML, CSS

## Additional Information (if available):
If there are any specific guidelines or requirements for contributing to the repository, please provide the necessary details.

**Comment by aayush105** [comment]
@purnasth there is already 11 loaders in the repository. can you do some new project ?

**Comment by purnasth** [comment]
Will the CSS loader but with your name animation work? I didn't see any of this kind on the README @aayush105

**Comment by aayush105** [comment]
> Will the CSS loader but with your name animation work? I didn't see any of this kind on the README @aayush105

Sure you can work on that type of loader @purnasth
