### ISSUE TITLE
Add responsive Navbar with a sidebar on phone screens

### ISSUE THREAD

**Issue by CodeBurnerProgramming** [you-dont-need/You-Dont-Need-JavaScript#346]
Make a responsive Navbar that only uses HTML and CSS or TailwindCSS but no Javascript!!

**Comment by parthasdey2304** [comment]
Would you please assign that to me!

**Comment by aayush105** [comment]
> Would you please assign that to me!

@parthasdey2304 you can work in it and create a PR.

**Comment by parthasdey2304** [comment]
@aayush105 I have fixed the issue would you please merge this!

**Comment by aayush105** [comment]
> @aayush105 I have fixed the issue would you please merge this!

@parthasdey2304 there is a conflict again. Please resolve it and I will merge it.
