### ISSUE TITLE
Arrow and different symbols using PURE CSS

### ISSUE THREAD

**Issue by VaibhavSharma24** [you-dont-need/You-Dont-Need-JavaScript#388]
**What i want to add ?**

Optimizing website is a real task sometimes we want to remove the number of images or icons from our website so I want to add some content with code on how you can easily make different symbols like arrow, square, pointer with PURE CSS and how CSS is more powerful than js.

**Comment by aayush105** [comment]
@VaibhavSharma24 you can work on this and create i PR. I will assign this issue to you.

**Comment by Shashankpantiitbhilai** [comment]
I am interested ,please assign it to me

**Comment by VaibhavSharma24** [comment]
@aayush105  Thank You soo much for assigning me I have started working on it and will keep you updated

**Comment by VaibhavSharma24** [comment]
> I am interested ,please assign it to me

@Shashankpantiitbhilai Loved your enthusiasm shashank but currently I am working on this issue. Feel free to go and find other issues where you can contribute on. All the best

**Comment by VaibhavSharma24** [comment]
#394 Just letting you know that i have made the PR for this issue @aayush105
