### ISSUE TITLE
Want to add a sliced button 

### ISSUE THREAD

**Issue by BALASARVAN12** [you-dont-need/You-Dont-Need-JavaScript#393]
I want To introduce a new button style called a "Sliced Button." This button should have a unique appearance compared to our existing buttons, giving users a clear indication that it's meant for a different action or purpose.

Please assign me this issue under HacktoberFest2023. 

**prototype**:
![image](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/91976828/50957a03-5020-4c2d-9889-c967ba5a2670)
![image](https://github.com/you-dont-need/You-Dont-Need-JavaScript/assets/91976828/dded0149-078d-4395-8dbc-71bbe0ed6341)

**Comment by aayush105** [comment]
@BALASARVAN12 i have assigned to you, you can work on it and create a PR.

**Comment by Tabindanoor** [comment]
i want to do it please assign it to me

**Comment by Tabindanoor** [comment]
i have done with it on fork

**Comment by aayush105** [comment]
> i have done with it on fork

Create a PR if you have done it I will merge it and close the issue.

**Comment by Tabindanoor** [comment]
@aayush105  did it

**Comment by Jenish-1235** [comment]
I would like to contribute for this issue, under hacktoberfest 2024. Could let me know, is this issue still open? If yes, please assign it to me under hacktoberfest 2024.

**Comment by aayush105** [comment]
@Jenish-1235 you can create you own issues if you have any or else you can just contribute to the repo without using the JavaScript. I will review it and merge it if everything is all good. 😊😊

**Comment by Jenish-1235** [comment]
> @Jenish-1235 you can create you own issues if you have any or else you can just contribute to the repo without using the JavaScript. I will review it and merge it if everything is all good. 😊😊

So basically, I can provide PR for any one my good designs made using only html and css and that makes a valid PR to contribute, am I getting it right ?

**Comment by aayush105** [comment]
> > @Jenish-1235 you can create you own issues if you have any or else you can just contribute to the repo without using the JavaScript. I will review it and merge it if everything is all good. 😊😊
> 
> So basically, I can provide PR for any one my good designs made using only html and css and that makes a valid PR to contribute, am I getting it right ?

yes, you getting it right broda!!! You create the design under the respective folder according to your category of design if it don't fall under the any category then create new folder and then make the PR.

**Comment by Jenish-1235** [comment]
Thanks dude, expects lots of PRs from me during hacktoberfest. 😁✌️ I love html css.
