### ISSUE TITLE
Creating a website with Dark and Light modes

### ISSUE THREAD

**Issue by Inija-2503** [you-dont-need/You-Dont-Need-JavaScript#448]
@aayush105 I would like to create a website with switch modes between light and dark modes. Assign me this issue i would like to bring a very  artistic design.

**Comment by aayush105** [comment]
> @aayush105 I would like to create a website with switch modes between light and dark modes. Assign me this issue i would like to bring a very artistic design.

Sure , I have assigned it to you, you can work on it and also while creating the PR follow the guidelines of CONTRIBUTING.md file and also provide the output of the image.

**Comment by Inija-2503** [comment]
@aayush105 can u assign the issue under the label hacktoberfest

**Comment by aayush105** [comment]
> @aayush105 can u assign the issue under the label hacktoberfest

@Inija-2503 The repository is already under the label of hacktoberfest, so you can contribute it.

**Comment by Omowunmikamil** [comment]
Good morning, @aayush105 I would like to work on this issue
Can I still work on this?

**Comment by aayush105** [comment]
> Good morning, @aayush105 I would like to work on this issue Can I still work on this?

Sure @Omowunmikamil you can work on this!! while creating the PR follow the guidelines of CONTRIBUTING.md file and also provide the output of the image.

**Comment by Inija-2503** [comment]
> > @aayush105 can u assign the issue under the label hacktoberfest
> 
> @Inija-2503 The repository is already under the label of hacktoberfest, so you can contribute it.

ok thank you
