### ISSUE TITLE
todo list contains javascript mixed with jade

### ISSUE THREAD

**Issue by dolohow** [you-dont-need/You-Dont-Need-JavaScript#45]

**Comment by stevemao** [comment]
@dolohow PR welcome to fix this.

**Comment by SamsShow** [comment]
I have fixed this issue in #157 

The previous Todo List was created using javascript mixed with Jade

- [x]  Todo List made using pure CSS
- [x]  Fixes Issue#45

**Comment by SamsShow** [comment]
fix:TodoList Updated #157
