### ISSUE TITLE
Profile Cards

### ISSUE THREAD

**Issue by pravin435916** [you-dont-need/You-Dont-Need-JavaScript#450]
i want to add 2-5 profile card templates. which looks attractive and good for creative websites we can use anywhere in the website 
# Hey can you assign me this issue with hactoberfest label :)

**Comment by Abhishek-Royy** [comment]
please assign me``

**Comment by S-125** [comment]
Please assign this to me

**Comment by Piyushsahu99** [comment]
### **can you pls assign this issue to me .**

I am so much intrested to work on this issue can you pls assign it to me , as i have a previous experience how to build Profile card and i have do a lot of project on this particular issue .

**Comment by dipsonishikha** [comment]
hey i am intrested in contributing in this.please assign it to me.

**Comment by Piyushsahu99** [comment]
Sure
