### ISSUE TITLE
Adding MultiLanguage Facility

### ISSUE THREAD

**Issue by Ojas-Arora** [you-dont-need/You-Dont-Need-JavaScript#459]
@aayush105 I want to add MultiLanguage Facility to it. Kindly assign me this issue.

**Comment by aayush105** [comment]
> @aayush105 I want to add MultiLanguage Facility to it. Kindly assign me this issue.

Please write the clear title for the issue, unable to get the title you have written. Like what multilanguage facility you want to add and where you want to add?

write the clear description about it, then if it is a good issue i will assign it to you and you can work in it.

**Comment by Ojas-Arora** [comment]
@aayush105 Multilanguage Facility means adding an option which can change the language of the page to the desired language in which anyone wants to read the website likhe hindi,spanish,french etc.

**Comment by aayush105** [comment]
> @aayush105 Multilanguage Facility means adding an option which can change the language of the page to the desired language in which anyone wants to read the website likhe hindi,spanish,french etc.

so you want to add this in the main index.html right?

**Comment by Ojas-Arora** [comment]
yes

**Comment by aayush105** [comment]
This issue is already being solved. So closing this issue.
