### ISSUE TITLE
Adding Toggle Functionality in the Main Page

### ISSUE THREAD

**Issue by Ojas-Arora** [you-dont-need/You-Dont-Need-JavaScript#468]
@aayush105 I want to add Toggle Theme Functionality for dark and light mode in the Main Page. Kindly assign me this issue.

**Comment by Ojas-Arora** [comment]
This is like I will make.

https://github.com/user-attachments/assets/b935731a-13fd-4f45-a4ea-552acfb3aa46

**Comment by aayush105** [comment]
This functionality is already been done, so closing this issue.
