### ISSUE TITLE
The CSS file not linked for the Login page

### ISSUE THREAD

**Issue by aryan04dbz** [you-dont-need/You-Dont-Need-JavaScript#469]
The CSS file is not properly linked as the name of the file is typed wrong so the CSS is not loaded into the HTML file . The positioning of the login box is also not at center so I can fix it . The page is not responsive too so I can make it responsive

### Before correction

![image](https://github.com/user-attachments/assets/31afa910-c919-47bb-aa9b-d3e7e2b2b7a5)

### After correction 

![image](https://github.com/user-attachments/assets/6feb21af-d16c-44c4-8b61-99294ce6e14e)

**Comment by aryan04dbz** [comment]
assign this issue to me @aayush105

**Comment by NAMAN-Github01** [comment]
please assign this issue to me
