### ISSUE TITLE
Add New Example: “Interactive Image Gallery” to You Don’t Need JavaScript

### ISSUE THREAD

**Issue by ChandraDevs1** [you-dont-need/You-Dont-Need-JavaScript#476]
**Description:**
I would like to contribute a new feature that demonstrates an Interactive Image Gallery using only HTML and CSS, without the need for JavaScript. This feature will showcase responsive image grid layouts, hover effects, and click-based image expansion for enhanced user interaction, aligning with the project’s goals of achieving functionality without JavaScript. Kindly assign this issue to me.

**Tag:**
@aayush105 please assign this to me.

**Comment by aayush105** [comment]
> **Description:** I would like to contribute a new feature that demonstrates an Interactive Image Gallery using only HTML and CSS, without the need for JavaScript. This feature will showcase responsive image grid layouts, hover effects, and click-based image expansion for enhanced user interaction, aligning with the project’s goals of achieving functionality without JavaScript. Kindly assign this issue to me.
> 
> **Tag:** @aayush105 please assign this to me.

@ChandraDevs1 i have assigned it to you, and while creating a PR request please upload the demo video or image in the README.md file as well as in the description.
