### ISSUE TITLE
improve the CSS toggle menu 

### ISSUE THREAD

**Issue by shuhaki** [you-dont-need/You-Dont-Need-JavaScript#477]
improve the CSS toggle menu after click on plus button the color is doesn't match with background color and the box is not completelyy filled up

<img width="1440" alt="Screenshot 2024-10-04 at 10 32 18 AM" src="https://github.com/user-attachments/assets/8b0aca87-8faf-4592-aff5-9d4056833b65">

PLEASE ASSIGN ME.

**Comment by ChandraDevs1** [comment]
@aayush105  Can you assign to me

**Comment by aayush105** [comment]
This issue is already been solved, so closing this issue.
