### ISSUE TITLE
Add a live link for the project

### ISSUE THREAD

**Issue by anniepauline** [you-dont-need/You-Dont-Need-JavaScript#483]
It would be great if the project is deployed so that others can see the working of the project

**Comment by aayush105** [comment]
> It would be great if the project is deployed so that others can see the working of the project

you can work in it, if you want to work.

**Comment by vinitvijal** [comment]
I want to work on it, please assign it to me under hacktoberfest

**Comment by aayush105** [comment]
> I want to work on it, please assign it to me under hacktoberfest

Ok you can work on it @vinitvijal , create Pr once you solve this issue.

**Comment by hirehamir** [comment]
I was about to open an issue for something similar. Where can users find the live link?
