### ISSUE TITLE
Enhancing the User Interface of Main Page of Website

### ISSUE THREAD

**Issue by Garv0504** [you-dont-need/You-Dont-Need-JavaScript#488]
I want to work on the UI/UX part of the main website. According to me the layout and UI of current website is not that much catchy and appealing for a user to try out the tools. Kindly assign me the task so that I can move forward for the same. @aayush105 kindly guide me with the changes available for the website.

**Comment by aayush105** [comment]
> I want to work on the UI/UX part of the main website. According to me the layout and UI of current website is not that much catchy and appealing for a user to try out the tools. Kindly assign me the task so that I can move forward for the same. @aayush105 kindly guide me with the changes available for the website.

Done!! you can start working on that @Garv0504 , before working update your forked repo branch and pull the main branch to avoid file coflict.

**Comment by Garv0504** [comment]
sure @aayush105 I am looking forward for the changes and revert you back.

**Comment by aayush105** [comment]
This issue is already been solved and the ui enhancement is done so cool by our contributors @Garv0504  and @ArjunCodess , so closing this issue.
