### ISSUE TITLE
Add more profile cards 

### ISSUE THREAD

**Issue by pravin435916** [you-dont-need/You-Dont-Need-JavaScript#492]
i created pull request with more cards in proper structured format and updated readme.MD

can you check my pr #472 and merge it

this is my 2nd pr

**Comment by pravin435916** [comment]
can you check my pr #472  and merge it
Thank you :)

**Comment by aayush105** [comment]
There is already a bunch of card design, but if you can create the more distinguishable design beside those design you can create a PR with the output image added in your respective folder under  the images section.
