### ISSUE TITLE
Adding image slider gallery for Image-Gallery-2 

### ISSUE THREAD

**Issue by priyagupta20044** [you-dont-need/You-Dont-Need-JavaScript#499]
Hi, I want to add a sliding image gallery using CSS and basic JavaScript. There will be two buttons, and clicking on each will reveal hidden images by sliding them in from the other side. 

Kindly assign me the issue with the **hacktoberfest** label 
I have attached a video explaining my approach and how it is going to look like. 
Video : 
https://github.com/user-attachments/assets/83edb84b-02dc-45e0-bf01-44763ed2fc8b

Screenshot of the above mentioned section : ![Screenshot 2024-10-05 200604](https://github.com/user-attachments/assets/e2a6e428-4062-4508-9844-8269fed22264)

**Comment by aayush105** [comment]
> Hi, I want to add a sliding image gallery using CSS and basic JavaScript. There will be two buttons, and clicking on each will reveal hidden images by sliding them in from the other side.
> 
> Kindly assign me the issue with the **hacktoberfest** label I have attached a video explaining my approach and how it is going to look like. Video : https://github.com/user-attachments/assets/83edb84b-02dc-45e0-bf01-44763ed2fc8b
> 
> Screenshot of the above mentioned section : ![Screenshot 2024-10-05 200604](https://private-user-images.githubusercontent.com/121642923/373880366-e2a6e428-4062-4508-9844-8269fed22264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxOTQ2MzYsIm5iZiI6MTcyODE5NDMzNiwicGF0aCI6Ii8xMjE2NDI5MjMvMzczODgwMzY2LWUyYTZlNDI4LTQwNjItNDUwOC05ODQ0LTgyNjlmZWQyMjI2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwNTU4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjYwNWVhNmJiNzc0OTM5ZTcxNjE4YWY0OTNhMWU1OWRkZWU4YzYwODU0MDVmMmFlMjI2YWMxY2VlMzkwZmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mHMz8UYrej_Cr9GISBxG42R3MMDKcNvtg9GyVebaxV4)

JS is not allowed in this repository, so this will be accepted. Only pure HTML and CSS is accepetd.
