### ISSUE TITLE
Enhancing the features of Author page

### ISSUE THREAD

**Issue by priyagupta20044** [you-dont-need/You-Dont-Need-JavaScript#500]
Hi, I want to add some new features to make the page look more attractive. I am proposing the following changes: 
1. Adding moving animations 
2. Adding a better way to add the picture of the author 
3. Adding more weight and making the font readable 
4. Adding moving icons to represent the tech stacks the author is familiar with 

Please assign this issue to me with the **Hacktoberfest** label

**Comment by aayush105** [comment]
> Hi, I want to add some new features to make the page look more attractive. I am proposing the following changes:
> 
> 1. Adding moving animations
> 2. Adding a better way to add the picture of the author
> 3. Adding more weight and making the font readable
> 4. Adding moving icons to represent the tech stacks the author is familiar with
> 
> Please assign this issue to me with the **Hacktoberfest** label

Ok you can work on it and show the demo of your updated code in the description section.

**Comment by dipsonishikha** [comment]
I am interested in solving the issue.please assign me under hacktober tag.

**Comment by aayush105** [comment]
> I am interested in solving the issue.please assign me under hacktober tag.
You can work on it and create a PR @dipsonishikha . Also add the output image under the respective folder as well in the description of the PR.

**Comment by dipsonishikha** [comment]
> > I am interested in solving the issue.please assign me under hacktober tag.
> > You can work on it and create a PR @dipsonishikha . Also add the output image under the respective folder as well in the description of the PR.

Will it count in hacktober fest.

**Comment by aayush105** [comment]
> > > I am interested in solving the issue.please assign me under hacktober tag.
> > > You can work on it and create a PR @dipsonishikha . Also add the output image under the respective folder as well in the description of the PR.
> 
> Will it count in hacktober fest.

Yes, it will be counted. @dipsonishikha

**Comment by drainbadenergy** [comment]
I would love to work on this issue!
