### ISSUE TITLE
Added hover effect of examples

### ISSUE THREAD

**Issue by shuhaki** [you-dont-need/You-Dont-Need-JavaScript#502]
Added hover effect of examples , 

<img width="1440" alt="Screenshot 2024-10-06 at 12 30 33 AM" src="https://github.com/user-attachments/assets/0b238b41-8d95-4058-a93b-7363a0cb20d1">

**Comment by aayush105** [comment]
> Added hover effect of examples ,
> 
> <img alt="Screenshot 2024-10-06 at 12 30 33 AM" width="1440" src="https://private-user-images.githubusercontent.com/145912232/373899305-0b238b41-8d95-4058-a93b-7363a0cb20d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxOTQ3ODEsIm5iZiI6MTcyODE5NDQ4MSwicGF0aCI6Ii8xNDU5MTIyMzIvMzczODk5MzA1LTBiMjM4YjQxLThkOTUtNDA1OC1hOTNiLTczNjNhMGNiMjBkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwNjAxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGQ0MjExZTEyMGFjOWZlNTk2NTY5YTU5OThkOTJhYTFkMTNjYTYwY2JkODY2YzlkYjlkYTE3ZjliZmNiNDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.63WlXNJVouX2-XrjRrxL0S5FGzKAa5ZuBfcdaDNJOe4">

where did you use the hover effect? can you show the demo video?

**Comment by aayush105** [comment]
This functionality is already been done by the other contributors, so closing this issue.
