### ISSUE TITLE
Add some features to Captain America Shield

### ISSUE THREAD

**Issue by rocky4446** [you-dont-need/You-Dont-Need-JavaScript#506]
Hi , I was looking through the Captain America shield project . I am thinking of adding some features like:
> add some animation to the star inside the shield 
>change color of the shield
>maybe add some mine own features

Please assign this issue to me under Hacktoberfest Label.

**Comment by aayush105** [comment]
> Hi , I was looking through the Captain America shield project . I am thinking of adding some features like:
> 
> > add some animation to the star inside the shield
> > change color of the shield
> > maybe add some mine own features
> 
> Please assign this issue to me under Hacktoberfest Label.

OK you can work on it and please upload the output demo video in the description while creating a PR and also in the images section of your project.

**Comment by Priya-rai121** [comment]
Hi, I have some idea that I think could really improve  the Captain America shield project.
Please assign this issue to me with the hacktoberfest label.

**Comment by aayush105** [comment]
> Hi, I have some ideas that I think could improve this project. Please assign this issue to me with the Hacktoberfest label

work on it who ever does 1st and best will be merged. Add the all necessary output gif or images as well.

**Comment by rocky4446** [comment]
I have sent the pull request to  the required project .
here is the link of the pull request:
https://github.com/you-dont-need/You-Dont-Need-JavaScript/pull/518
