### ISSUE TITLE
Use relative path instead of absolute path in <img /> tags

### ISSUE THREAD

**Issue by manoj9896** [you-dont-need/You-Dont-Need-JavaScript#513]
In the deployed version, images are not displaying. The issue arises because we are using absolute paths in the `<img>` tags. 

![Screenshot 2024-10-06 at 4 20 01 PM](https://github.com/user-attachments/assets/ef3160b8-2692-4f44-8228-421c2b8b3d7b)

![Screenshot 2024-10-06 at 4 20 16 PM](https://github.com/user-attachments/assets/a3bb740c-08d4-481d-8d72-80a91e8f5146)

For instance, in the file `misc/ImageHoverGallery.html`, we use an absolute path to load the image `4.png`, as shown below:

```html
<div class="box">
   <img src="/images/4.png" alt="">
</div>
```

This works fine locally but causes issues in the deployed version.

### Solution:
We can resolve this by using a relative path to reference the image `4.png`, like so:

```html
<div class="box">
   <img src="../images/4.png" alt="">
</div>
```

I have tested this solution on GitHub Pages (you can check it here: [GitHub Pages example](https://manoj9896.github.io/experiments-with-html/)) and confirmed it works.

I would love to work on this issue. Could you please assign it to me?

**Comment by manoj9896** [comment]
@aayush105 I found this issue in two files .

1. `misc/ImageHoverGallery.html`
2. `misc/movingroad.html`

**Comment by aayush105** [comment]
> @aayush105 I found this issue in two files .
> 
> 1. `misc/ImageHoverGallery.html`
> 2. `misc/movingroad.html`

If you want to solve this issue than you can move forward on this issue and create a PR. @manoj9896

**Comment by manoj9896** [comment]
@aayush105 I've created a PR to address the issue mentioned above. Please review it and let me know if any changes or fixes are needed.

**Comment by aayush105** [comment]
> @aayush105 I've created a PR to address the issue mentioned above. Please review it and let me know if any changes or fixes are needed.

Your PR is already been merged. @manoj9896 
And closing this issue as completed.
