### ISSUE TITLE
Adding The github link in portfolio so that it will redirect it to this github

### ISSUE THREAD

**Issue by Kedar-sonavani** [you-dont-need/You-Dont-Need-JavaScript#519]
Also deleting the extra footer buttons
Please assign this issue to me with the Hacktoberfest label

**Comment by aniketdoke35** [comment]
hey @aayush105, iam interested in this issue, can you assign issue to me..

**Comment by drainbadenergy** [comment]
I am working on this issue and also fixing the typo's on the website!
