### ISSUE TITLE
Interested to join https://github.com/you-dont-need ?

### ISSUE THREAD

**Issue by cht8687** [you-dont-need/You-Dont-Need-Javascript#52]
Hi, this is a nice repo. Are you interested to join https://github.com/you-dont-need ? :smile:

**Comment by NamPNQ** [comment]
yes, sure, np with me

**Comment by stevemao** [comment]
@NamPNQ sent you an invite. You'll be an owner of the org. Would you like to transfer the repo? Cheers!
