### ISSUE TITLE
Adding weather forecast and analog calendar in Miscellaneous 

### ISSUE THREAD

**Issue by VipulNerd** [you-dont-need/You-Dont-Need-JavaScript#527]
Hello @aayush105  I want to add some extra feature in Miscellaneous. The features are analog calendars depicting dates, months, and years. Also, I can add a real-time weather forecast system that can be used by others on there site. Please assign the task to me.

**Comment by aayush105** [comment]
> Hello @aayush105 I want to add some extra feature in Miscellaneous. The features are analog calendars depicting dates, months, and years. Also, I can add a real-time weather forecast system that can be used by others on there site. Please assign the task to me.

Is it done by using only pure HTML and CSS?

**Comment by VipulNerd** [comment]
Yes, I can do that.

**Comment by aayush105** [comment]
> Yes, I can do that.

Ok, you can work on it and once completed make the PR, and include output image of your code under your respective folder and also add gif video in the description if you can else add all the screenshots.
@VipulNerd

**Comment by VipulNerd** [comment]
@aayush105 I have created the PR for the calendar and weather template. Please try to review it and if possible please accept the PR. Thanks and regards.

**Comment by aayush105** [comment]
> @aayush105 I have created the PR for the calendar and weather template. Please try to review it and if possible please accept the PR. Thanks and regards.

Yes i saw it and already been merged. @VipulNerd
