### ISSUE TITLE
new project only with css and html

### ISSUE THREAD

**Issue by Ashu-tosh1** [you-dont-need/You-Dont-Need-JavaScript#528]
Hey @aayush105,I can add a songplayer website in website folder section using only css and html,so please assign me this task.

**Comment by aayush105** [comment]
> Hey @aayush105,I can add a songplayer website in website folder section using only css and html,so please assign me this task.

Ok you can work on it and create a PR. Also add the output images in your respective folder as well as in the description of PR.
@Ashu-tosh1

**Comment by aayush105** [comment]
> Hey. Can I do A animated button with html and css?

Yes, you can do.
