### ISSUE TITLE
Dark Mode State Not Persisting on Navigation

### ISSUE THREAD

**Issue by ozearkhan** [you-dont-need/You-Dont-Need-JavaScript#547]
When a user activates dark mode and then navigates to a different page (by clicking on an element), 

> **_the dark mode visually deactivates upon returning to the main page using the browser's back button._**

 The dark mode toggle switch remains in the “on” position, but the page appears in light mode. Toggling the switch off and on again temporarily fixes the issue, but the problem recurs when navigating to a new page and back.

### Steps to Reproduce:

1. Open the main page.
2. Activate dark mode.
3. Click on any element to navigate to a new page.
4. Use the browser's back button to return to the main page.
5. Observe that the page is in light mode, but the dark mode toggle is still "on."

### Expected Behavior:
Dark mode should persist when navigating between pages and remain active when returning via the back button.

### Actual Behavior:
The page reverts to light mode visually, while the dark mode toggle remains in the "on" position.
![image](https://github.com/user-attachments/assets/035f7b1d-3df4-41d2-8226-76c1cd41cf5c)

### Proposed solution:
if permissible, I can generate a pull request with my solution.

**Comment by ozearkhan** [comment]
hi @aayush105 , 
I've noticed the issue with dark mode deactivating upon returning to the main page (#547) and I'd like to work on fixing it. Could you please assign this issue to me?

**Comment by Sonu0305** [comment]
hi **@aayush105** , 
i have already solved this issue, please look into the same 
Thank You
[Uploading videoclip.webm…]()
