### ISSUE TITLE
Enhancement of Theme Toggle Button Position and Style on Main Page

### ISSUE THREAD

**Issue by ms-solly** [you-dont-need/You-Dont-Need-JavaScript#572]
I’d like to improve the main page by adjusting both the positioning and styling of the theme toggle button. Currently, the button overlaps with the page section border, and I propose a couple of potential fixes:

1. Reposition the button to either outside the page section or inside it for a cleaner layout, or alternatively, set it to be absolutely positioned instead of fixed.
2. Update the button's style to align better with the overall theme and improve its aesthetics.

These changes aim to enhance both the usability and visual consistency of the page.
@aayush105 Could you please assign this issue to me with the Hacktoberfest label? 
Looking forward to contributing to this improvement!

**Comment by aayush105** [comment]
> I’d like to improve the main page by adjusting both the positioning and styling of the theme toggle button. Currently, the button overlaps with the page section border, and I propose a couple of potential fixes:
> 
> 1. Reposition the button to either outside the page section or inside it for a cleaner layout, or alternatively, set it to be absolutely positioned instead of fixed.
> 2. Update the button's style to align better with the overall theme and improve its aesthetics.
> 
> These changes aim to enhance both the usability and visual consistency of the page. @aayush105 Could you please assign this issue to me with the Hacktoberfest label? Looking forward to contributing to this improvement!

Sure, you can work on it and create a PR.

**Comment by ms-solly** [comment]
#574

**Comment by violin87** [comment]
Hi! Can you assign this issue to me please?

**Comment by ms-solly** [comment]
@git-sidd @violin87 , this issue has been resolved. Closing it now.
