### ISSUE TITLE
MakeMyTrip clone using HTML,CSS

### ISSUE THREAD

**Issue by meetarora10** [you-dont-need/You-Dont-Need-JavaScript#580]
Want to add MakeMyTrip clone using HTML,CSS only . It contains different sections with a navbar and is completely responsive.

**Comment by WizCoderr** [comment]
Just wanted to ask, if you want a full working MMT clone with working backend or just a prototyped frontend

**Comment by meetarora10** [comment]
> Just wanted to ask, if you want a full working MMT clone with working backend or just a prototyped frontend

With HTML,CSS only frontend is possible

**Comment by WizCoderr** [comment]
Please assign me this project under Hackctober fest label.

**Comment by meetarora10** [comment]
@aayush105 kindly consider this issue.

**Comment by WizCoderr** [comment]
@aayush105 can you please assign this to me under Hacktoberfest label

**Comment by aayush105** [comment]
Create a PR who ever creates 1st will be accepted.
