### ISSUE TITLE
[New Feature] A Quizz Website Using HTML,CSS and JS

### ISSUE THREAD

**Issue by aniketraut16** [you-dont-need/You-Dont-Need-JavaScript#581]
### 📝 Feature Description  
I would like to add a quiz app as a new component to the repository. The app will consist of multiple-choice questions, score tracking, and user-friendly UI built with HTML, CSS, and JavaScript.

### 🎯 Expected Behavior  
- The user can take a quiz by selecting answers from multiple-choice options.
- The app should keep track of the user’s score and display the result at the end.
- The app should be responsive and compatible across various devices.
- Clean code structure to facilitate easy integration with other components.

### ✨ Additional Features  
- Randomization of questions and answers.
- A timer for quiz completion.
- Option to reset the quiz and try again.
  
### 📑 Proposed Solution  
The quiz app will be developed using vanilla HTML, CSS, and JavaScript. It will be added as a separate component/module within the repository. The feature will include modular functions for handling quiz logic, UI updates, and result calculations.

### 📋 Checklist  
- [ ] The feature adds new functionality without affecting other components.
- [ ] The feature is thoroughly tested and documented.
- [ ] The UI is designed to be responsive.

**Comment by DipeshK47** [comment]
I would love to work on it. /assign
