### ISSUE TITLE
Adding Netflix Clone

### ISSUE THREAD

**Issue by NAMAN-Github01** [you-dont-need/You-Dont-Need-JavaScript#616]
I want to add a Netflix clone created by me using HTML and CSS only, please assign me this issue under hactoberfest2024

**Comment by narayan123git** [comment]
I have already created a Netflix Clone, Please assign this to me.

**Comment by aayush105** [comment]
Create a PR.

**Comment by NAMAN-Github01** [comment]
> Create a PR.

Done
