### ISSUE TITLE
Lightbulb animation not functioning

### ISSUE THREAD

**Issue by simd1** [you-dont-need/You-Dont-Need-JavaScript#629]
# Issue:
When "light bulb animation" is clicked a blank screen appears

## **Issue Video:**
[issue.webm](https://github.com/user-attachments/assets/eaecb732-ac4b-468d-af5e-076a4ac9fea8)

**Comment by AryanVBW** [comment]
fix light bulb naiamtion #633

**Comment by AryanVBW** [comment]
https://github.com/user-attachments/assets/f0ebf1e7-f181-4921-9bad-27d258a8a162
