### ISSUE TITLE
Animated profile card

### ISSUE THREAD

**Issue by amrutha-m206** [you-dont-need/You-Dont-Need-JavaScript#639]
An animated profile card with hover effects which could be used for introducing a person's profile

**Comment by KhanjarSingh** [comment]
@amrutha-m206 can i work on this under the tag hacktoberfest

**Comment by OsuraHansaja** [comment]
Hi @amrutha-m206 ,

I've completed the animated profile card for issue #639. 
It's a profile card for a social media platform with user preference categories and signatures that can be shared.
It includes:
- Hover effects on categories, signature text, and profile picture.
- Responsive design using media queries.
- Follow and Message buttons with hover effects.

I've submitted a pull request #658 for review. Let me know if any changes are needed!

Thanks!

**Comment by KhanjarSingh** [comment]
ooh sry
