### ISSUE TITLE
Adding a automatic sliding image system using CSS

### ISSUE THREAD

**Issue by drainbadenergy** [you-dont-need/You-Dont-Need-JavaScript#645]
A webpage that can will have a navigation bar at the top and automatic sliding images, with scrolling down leading to more facts , and the page ending with a redirect to other pages of the same organization.

Can you kindly assign me this issue with hacktoberfest label? @aayush105

**Comment by Simmi019** [comment]
i would like to work on this ..kindly assign me this under hacktoberfest label

**Comment by tanishkagupta27** [comment]
I want to work on this issue.
Can you please assign it to me.

**Comment by aayush105** [comment]
> A webpage that can will have a navigation bar at the top and automatic sliding images, with scrolling down leading to more facts , and the page ending with a redirect to other pages of the same organization.
> 
> Can you kindly assign me this issue with hacktoberfest label? @aayush105

Ok i have assigned it to you.
