### ISSUE TITLE
[ADD GAME] Duel of Wits

### ISSUE THREAD

**Issue by byteom** [you-dont-need/You-Dont-Need-JavaScript#679]
# Duel of Wits

**Duel of Wits** is a simple, fun, and interactive two-player trivia game built using HTML, CSS, and JavaScript. Players take turns answering questions from a variety of categories, testing their general knowledge. The player who answers the most questions correctly wins!

## Game Features

- **Two Players**: Play against a friend in alternating turns.
- **Trivia Questions**: Test your knowledge with multiple-choice questions on various topics.
- **Scoring System**: Keep track of scores for each player.
- **Dynamic Gameplay**: Each player answers a question, and the game automatically switches turns.
- **Win Condition**: The game announces the winner at the end based on correct answers, or declares a tie if scores are even.

## How to Play

1. Press the "Start Game" button to begin.
2. Player 1 will be asked a question with four possible answers.
3. Choose the correct answer to score points.
4. The game alternates between Player 1 and Player 2 for each question.
5. After all questions are answered, the player with the highest score wins the duel!

## Technologies Used

- **HTML** for the structure and layout of the game.
- **CSS** for styling the user interface.
- **JavaScript** for game logic, question handling, and score tracking.

Are you ready to challenge your friends and prove who's the smartest? Let the duel begin!

**Comment by aayush105** [comment]
JS is not allowed in this repository, so i am closing this issue.
create issue for only HTML and CSS projects
