### ISSUE TITLE
More than CSS!

### ISSUE THREAD

**Issue by ghost** [you-dont-need/You-Dont-Need-JavaScript#91]
There are more languages lurking out there that are also alternatives to JS that could be given a spotlight in this project. For example, PHP! Check out danwin/le-chat-php, as it is an entire functioning chat server. WebAssembly is also an upcoming supplement on the rise.

**Comment by KOLANICH** [comment]
wasm is not a replacement for JS because it is worse than JS. server-side computations is a well-known replacement for JS that was available before JS was invented.

**Comment by zach83** [comment]
Could you explain or reference how WASM is worse than JS?
Even if/how it is worse than JS, I still think the server-sided languages should still get some credit, for sure.
